[workspace]
# members = ["common", "app", "dealer", "dbs"]
members = [ "app"]
resolver = "2"

[workspace.dependencies]
dotenv = "*"
sea-orm = { version = "*", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
bytes = "*"
tokio = { version = "*" , features = ["full"]}
tokio-util = { version = "*", features = ["codec"] }
futures-util = { version = "*", features = ["sink"] }



