[package]
name = "dealer-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"]}
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"