[package]
name = "dealer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}
dbs = {path = "../dbs"}
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }